name: Flutter Build Web

permissions:
  contents: write
  pull-requests: write


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --wasm

      - name: Create CNAME File
        run: |
          cd build/web
          ls 
          echo "adding CNAME file"
          echo "dev.tejasgprod.online" > CNAME
          
      - name: Push to Build Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dev
          FOLDER: build/web
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
          
